### ISSUE TITLE
npm rebuild fails because of Windows dependency

### ISSUE THREAD

**Issue by grexe** [davidibl/dmnmgr-client#12]
The build and docs should be cross-platform. Both contain references to Windows, e.g. `npm rebuild` fails because of this line in `package.json`:
> "rebuild": ".\\node_modules\\.bin\\electron-rebuild.cmd"

(should be `node_modules/.bin/electron-rebuild` on Mac, also needs Xcode CLI Tools installed)

**Comment by davidibl** [comment]
@grexe 
Perhaps you can contribute a solution. I don't have a mac to test this. Or maybe you can support me by testing a branch?

**Comment by grexe** [comment]
sorry for the late reply, I found that my simple setup with stock Camunda modeller is sufficient for now, but would still be willing to help you out here.
I can support you with testing, have any branch ready?

**Comment by davidibl** [comment]
@grexe Should also be fixed by "fix_compilation_missing_mainjs" branch
